version: '3.8'

services:  
  faust_message_processor:
    image: python:3.10-slim
    container_name: faust_processor
    networks:
      - proxynet
    working_dir: /app
    volumes:
      - ./app:/app
    command: bash -c "pip install -r requirements.txt && python3 faust_processor.py worker -l INFO"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092

networks:
  proxynet:
    name: custom_network