{
 "title": "Debezium4",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "connector_type",
    "label": "Connector Type",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen"
    }
   },
   {
    "name": "connector_name",
    "label": "Connector Name",
    "query": {
     "query": "debezium_metrics_TotalNumberOfEventsSeen{plugin=\"$connector_type\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time since last event",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastevent{context=\"streaming\",name=\"customers\",plugin=\"postgres\",}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\",name=\"customers\",plugin=\"postgres\",}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_NumberOfEventsSkipped{context=\"streaming\",name=\"customers\",plugin=\"postgres\",}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_connected{context=\"streaming\",name=\"customers\",plugin=\"postgres\",}"
    }
   ]
  },
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totaltablecount{context=\"snapshot\",name=\"customers\",plugin=\"postgres\",}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Remaining tables",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_remainingtablecount{context=\"snapshot\",name=\"customers\",plugin=\"postgres\",}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotrunning{context=\"snapshot\",name=\"customers\",plugin=\"postgres\",}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotcompleted{context=\"snapshot\",name=\"customers\",plugin=\"postgres\",}"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotaborted{context=\"snapshot\",name=\"customers\",plugin=\"postgres\",}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\",name=\"customers\",plugin=\"postgres\",}",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Rows scanned",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "debezium_metrics_rowsscanned{context=\"snapshot\",name=\"customers\",plugin=\"postgres\",}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area='heap'}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area='heap'}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "Running" },
    { "expr": "jvm_threads_peak", "legendFormat": "Maximum" },
    { "expr": "jvm_threads_started_total", "legendFormat": "Started in total" }
   ]
  }
 ]
}