services:
 zookeeper-1:
   image: confluentinc/cp-zookeeper:7.4.4
   restart: always
   container_name: zookeeper-1
   hostname: zookeeper-1
   ports:
     - "2181:2181"
   volumes:
     - data-zookeeper-log-1:/var/lib/zookeeper/log
     - data-zookeeper-data-1:/var/lib/zookeeper/data
     - ./ssl:/etc/zookeeper/secrets
   networks:
     - confluent
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: "sasl"
     ZOOKEEPER_SASL_ENABLED: "true"
     KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
       -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
       -Dzookeeper.allowSaslFailedClients=false
       -Dzookeeper.requireClientAuthScheme=sasl
       -DjaasLoginRenew=3600000

 zookeeper-2:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    container_name: zookeeper-2
    hostname: zookeeper-2
    ports:
      - "2182:2182"
    volumes:
      - data-zookeeper-log-2:/var/lib/zookeeper/log
      - data-zookeeper-data-2:/var/lib/zookeeper/data
      - ./ssl:/etc/zookeeper/secrets
    networks:
      - confluent
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: "sasl"
      ZOOKEEPER_SASL_ENABLED: "true"
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
        -DjaasLoginRenew=3600000

 zookeeper-3:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    container_name: zookeeper-3
    hostname: zookeeper-3
    ports:
      - "2183:2183"
    volumes:
      - data-zookeeper-log-3:/var/lib/zookeeper/log
      - data-zookeeper-data-3:/var/lib/zookeeper/data
      - ./ssl:/etc/zookeeper/secrets
    networks:
      - confluent
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: "sasl"
      ZOOKEEPER_SASL_ENABLED: "true"
      ZOOKEEPER_AUTH_PROVIDER_1: "org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
        -DjaasLoginRenew=3600000

 kafka-1:
   image: confluentinc/cp-kafka:7.4.4
   restart: always
   container_name: kafka-1
   hostname: kafka-1
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   ports:
     - "9092:9092"
     - "9093:9093"
   networks:
     - confluent
   volumes:
     - data-kafka-1:/var/lib/kafka/data
     - ./ssl:/etc/kafka/secrets
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
     KAFKA_DELETE_TOPIC_ENABLE: true
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,SASL_SSL://0.0.0.0:9093
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,SASL_SSL://kafka-1:9093
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_SSL:SASL_SSL
     KAFKA_LISTENER_SECURITY_PROTOCOL: SASL_SSL
     KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
     KAFKA_SSL_KEYSTORE_FILENAME: kafka-1.keystore.pkcs12
     KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-1_keystore_creds
     KAFKA_SSL_KEY_CREDENTIALS: kafka-1_sslkey_creds
     KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-1.truststore.jks
     KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-1_truststore_creds
     KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
     KAFKA_SSL_CLIENT_AUTH: "required"
     # KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
     KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
     KAFKA_SUPER_USERS: "User:admin"
     KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
     # KAFKA_ZOOKEEPER_SASL_CLIENT: true
     KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka.sasl.jaas.conf"
     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"

 kafka-2:
   image: confluentinc/cp-kafka:7.4.4
   restart: always
   container_name: kafka-2
   hostname: kafka-2
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   ports:
     - "9094:9094"
     - "9095:9095"
   networks:
     - confluent
   volumes:
     - data-kafka-2:/var/lib/kafka/data
     - ./ssl:/etc/kafka/secrets
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
     KAFKA_DELETE_TOPIC_ENABLE: true
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,SASL_SSL://0.0.0.0:9095
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9094,SASL_SSL://kafka-2:9095
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_SSL:SASL_SSL
     KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
     KAFKA_LISTENER_SECURITY_PROTOCOL: SASL_SSL
     KAFKA_SSL_KEYSTORE_FILENAME: kafka-2.keystore.pkcs12
     KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-2_keystore_creds
     KAFKA_SSL_KEY_CREDENTIALS: kafka-2_sslkey_creds
     KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-2.truststore.jks
     KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-2_truststore_creds
     KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
     KAFKA_SSL_CLIENT_AUTH: "required"
     # KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
     KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
     KAFKA_SUPER_USERS: "User:admin"
     KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
     # KAFKA_ZOOKEEPER_SASL_CLIENT: true
     KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka.sasl.jaas.conf"
     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"

 kafka-3:
   image: confluentinc/cp-kafka:7.4.4
   restart: always
   container_name: kafka-3
   hostname: kafka-3
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   ports:
     - "9096:9096"
     - "9097:9097"
   networks:
     - confluent
   volumes:
     - data-kafka-3:/var/lib/kafka/data
     - ./ssl:/etc/kafka/secrets
   environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
     KAFKA_DELETE_TOPIC_ENABLE: true
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096,SASL_SSL://0.0.0.0:9097
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9096,SASL_SSL://kafka-3:9097
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_SSL:SASL_SSL
     KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
     KAFKA_LISTENER_SECURITY_PROTOCOL: SASL_SSL
     KAFKA_SSL_KEYSTORE_FILENAME: kafka-3.keystore.pkcs12
     KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-3_keystore_creds
     KAFKA_SSL_KEY_CREDENTIALS: kafka-3_sslkey_creds
     KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-3.truststore.jks
     KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-3_truststore_creds
     KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
     KAFKA_SSL_CLIENT_AUTH: "required"
    # KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
     KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
     KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
     KAFKA_SUPER_USERS: "User:admin"
    # KAFKA_ZOOKEEPER_SASL_CLIENT: true
     KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka.sasl.jaas.conf"
     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"

volumes:
  data-zookeeper-log-1:
  data-zookeeper-data-1:
  data-zookeeper-log-2:
  data-zookeeper-data-2:
  data-zookeeper-log-3:
  data-zookeeper-data-3:
  data-kafka-1:
  data-kafka-2:
  data-kafka-3:

networks:
 confluent:
  driver: bridge