services:
 nifi:
   image: apache/nifi:1.21.0
   container_name: nifi
   ports:
     - "8080:8080"
   networks:
     - confluent
   environment:
     NIFI_WEB_HTTP_PORT: 8080
   volumes:
     - ./nifi_data:/opt/nifi/nifi-current/data

 postgres:
   image: postgres:15
   container_name: postgres
   restart: always
   environment:
     POSTGRES_DB: mydatabase
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres_password
   ports:
     - "5432:5432"
   networks:
     - confluent
   volumes:
     - ./postgres_data:/var/lib/postgresql/data
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
 nifi_data:
 postgres_data:

networks:
 confluent: